### ISSUE TITLE
Erkunden der IT-Sammlung / Interview mit Ludwig Hitzenberger

### ISSUE THREAD

**Issue by Peacecake** [Peacecake/HoloMu#1]
Rahmenbedingungen klären:
- Welche Objekte eignen sich für unseren Prototypen?
- Gibt es Informationen liegen vor? Sind sie eventuell schon digitalisiert? Sind sie strukturiert?
- Können wir Objekte ausleihen?
- Sonstiger Input von Herrn Hitzenberger

**Comment by TobiHauser** [comment]
Erstes Treffen hat nicht stattgefunden. Erneutes Treffen vereinbaren! Anfrage läuft seit 20.06

**Comment by Peacecake** [comment]
Erneuter Termin am 11.07. mit Gruppe "Dialogflow"

**Comment by Peacecake** [comment]
Exponate sind ausgesucht und aufgebaut. Wir haben außerdem den Schlüssel und die Zugangsdaten zur Datenbank erhalten.
