### ISSUE TITLE
Problemstellung - fällig bis 29.06. um 23:55 Uhr

### ISSUE THREAD

**Issue by Peacecake** [Peacecake/HoloMu#2]
Erster Teil soll folgende Themen behandeln:
- eine aussagekräftige Motivation,
- eine Bedarfsanalyse für die Interaktion mit einem virtuellen Agenten
- einen Vergleich mit Arbeiten aus der Literatur
- eine Erläuterung, was Sie neu oder anders machen als in der Literatur beschrieben oder inwieweit Sie beschriebene Methoden auf ein neues Anwendungsproblem übertragen,

Länge: zwischen 5 und 7 Seiten

**Comment by TobiHauser** [comment]
I think it's ready for proofreading?

**Comment by Peacecake** [comment]
It is now;)
