### ISSUE TITLE
Object Recognition

### ISSUE THREAD

**Issue by TobiHauser** [Peacecake/HoloMu#20]
Object recognition works so far with test pictures

**Comment by TobiHauser** [comment]
next step: train model and test recognition with pictures for our use case with it-objects

**Comment by TobiHauser** [comment]
tf_files folder with bottlenecks and model can't be pushed because it's too large
- tf_files is in gitignore now
- we need to share our image files so that both of us can work with the same training data

**Comment by Peacecake** [comment]
Ok, das ist natürlich schlecht. Dann machen wir halt einen geteilten Dropbox Ordner, oder? Musst halt dann erklären, wo was hin muss...
